import { IColumns } from '@antmjs/vantui'

const defaultRender = (v) => v || '-'

export function useColumns() {
  const column: IColumns[] = [
    {
      title: '序号',
      dataIndex: 'index',
      fixed: 'left',
      align: 'center',
      width: 15,
      render: (_, payload, index) => <>{(index || 0) + 1}</>,
    },
    {
      title: '可报考本科专业',
      dataIndex: 'major',
      fixed: 'left',
      align: 'center',
      width: 35,
      render: defaultRender,
    },
    {
      title: '招生高校',
      dataIndex: 'enrollmentUniversitie',
      align: 'center',
      fixed: 'left',
      width: 45,
      render: defaultRender,
    },
    {
      title: '院校性质',
      align: 'center',
      dataIndex: 'educationalInstitution',
      width: 25,
      render: defaultRender,
    },
    {
      title: '联培学校',
      align: 'center',
      dataIndex: 'lianpeiSchool',
      width: 45,
      render: defaultRender,
    },
    {
      title: '招生计划',
      align: 'center',
      dataIndex: 'enrollmentPlan',
      width: 25,
      render: defaultRender,
    },
    {
      title: '普通计划',
      align: 'center',
      dataIndex: 'normalPlan',
      width: 25,
      render: defaultRender,
    },
    {
      title: '脱贫家庭',
      align: 'center',
      dataIndex: 'povertyAlleviationFamiliy',
      width: 25,
      render: defaultRender,
    },
    {
      title: '获奖学生',
      align: 'center',
      dataIndex: 'awardStudent',
      width: 25,
      render: defaultRender,
    },
    {
      title: '未来工匠',
      align: 'center',
      dataIndex: 'futureCraftsman',
      width: 25,
      render: defaultRender,
    },
    {
      title: '退役士兵',
      align: 'center',
      dataIndex: 'retiredSoldiers',
      width: 25,
      render: defaultRender,
    },
    {
      title: '考试科目公共课300分',
      align: 'center',
      dataIndex: 'exam300',
      width: 45,
      render: defaultRender,
    },
    {
      title: '考试科目专业课150分',
      align: 'center',
      dataIndex: 'exam150',
      width: 45,
      render: defaultRender,
    },
    {
      title: '学费',
      align: 'center',
      dataIndex: 'tuition',
      width: 20,
      render: defaultRender,
    },
    {
      title: '省控线',
      align: 'center',
      dataIndex: 'provincialControlLine',
      width: 30,
      render: defaultRender,
    },
    {
      title: '录取分数线普通考生',
      align: 'center',
      dataIndex: 'admissionScoreLineForOrdinaryCandidate',
      width: 45,
      render: defaultRender,
    },
    {
      title: '录取分数线脱贫家庭',
      align: 'center',
      dataIndex: 'admissionScorePovertyAlleviationFamilies',
      width: 45,
      render: defaultRender,
    },
    {
      title: '录取分数线获奖学生',
      align: 'center',
      dataIndex: 'admissionScoreLineAwardStudents',
      width: 45,
      render: defaultRender,
    },
    {
      title: '省控线分叉普通考生',
      align: 'center',
      dataIndex: 'provincialControlLineBranchOrdinaryCandidate',
      width: 45,
      render: defaultRender,
    },
    {
      title: '缺额计划普通考生',
      align: 'center',
      dataIndex: 'vacancyPlanRegularCandidate',
      width: 35,
      render: defaultRender,
    },
    {
      title: '缺额计划脱贫家庭',
      align: 'center',
      dataIndex: 'vacancyPlanPovertyAlleviationFamiliy',
      width: 35,
      render: defaultRender,
    },
    {
      title: '缺额计划获奖学生',
      align: 'center',
      dataIndex: 'vacancyProgramAwardStudents',
      width: 35,
      render: defaultRender,
    },
  ]

  return column;
}
