import { IColumns } from '@antmjs/vantui'

const defaultRender = (v) => v || '-'

export function useColumns() {
  const column: IColumns[] = [
    {
      title: '序号',
      dataIndex: 'index',
      fixed: 'left',
      align: 'center',
      width: 15,
      render: (_, payload, index) => <>{(index || 0) + 1}</>,
    },
    {
      title: '本科院校代码',
      dataIndex: 'schoolCode',
      fixed: 'left',
      align: 'center',
      width: 35,
      render: defaultRender,
    },
    {
      title: '招生高校',
      dataIndex: 'schoolName',
      align: 'center',
      fixed: 'left',
      width: 45,
      render: defaultRender,
    },
    {
      title: '院校性质',
      align: 'center',
      dataIndex: 'schoolType',
      width: 25,
      render: defaultRender,
    },
    {
      title: '联培学校',
      align: 'center',
      dataIndex: 'coSchool',
      width: 45,
      render: defaultRender,
    },
    {
      title: '本科专业代码',
      align: 'center',
      dataIndex: 'learnCode',
      width: 25,
      render: defaultRender,
    },
    {
      title: '本科专业',
      align: 'center',
      dataIndex: 'learn',
      width: 25,
      render: defaultRender,
    },
    {
      title: '招生计划',
      align: 'center',
      dataIndex: 'needNum',
      width: 25,
      render: defaultRender,
    },
    {
      title: '普通计划',
      align: 'center',
      dataIndex: 'ptNum',
      width: 25,
      render: defaultRender,
    },
    {
      title: '脱贫计划',
      align: 'center',
      dataIndex: 'tpNum',
      width: 25,
      render: defaultRender,
    },
    {
      title: '获奖学生',
      align: 'center',
      dataIndex: 'hjNum',
      width: 25,
      render: defaultRender,
    },
    {
      title: '未来工匠',
      align: 'center',
      dataIndex: 'gjNum',
      width: 25,
      render: defaultRender,
    },
    {
      title: '退役士兵',
      align: 'center',
      dataIndex: 'tyNum',
      width: 25,
      render: defaultRender,
    },
    {
      title: '考试科目',
      align: 'center',
      dataIndex: 'test',
      width: 45,
      render: defaultRender,
    },
    {
      title: '学费',
      align: 'center',
      dataIndex: 'cost',
      width: 20,
      render: defaultRender,
    },
    {
      title: '省控线',
      align: 'center',
      dataIndex: 'skx',
      width: 30,
      render: defaultRender,
    },
    {
      title: '退役缺额',
      align: 'center',
      dataIndex: 'tyqe',
      width: 45,
      render: defaultRender,
    },
    {
      title: '工匠缺额',
      align: 'center',
      dataIndex: 'gjqe',
      width: 45,
      render: defaultRender,
    },
    {
      title: '脱贫缺额',
      align: 'center',
      dataIndex: 'tpqe',
      width: 45,
      render: defaultRender,
    },
    {
      title: '获奖缺额',
      align: 'center',
      dataIndex: 'hjqe',
      width: 45,
      render: defaultRender,
    },
    {
      title: '普通缺额',
      align: 'center',
      dataIndex: 'ptqr',
      width: 35,
      render: defaultRender,
    },
    {
      title: '工匠录取分数',
      align: 'center',
      dataIndex: 'gjScore',
      width: 35,
      render: defaultRender,
    },
    {
      title: '脱贫录取分数',
      align: 'center',
      dataIndex: 'tpScore',
      width: 35,
      render: defaultRender,
    },
    {
      title: '获奖录取分数',
      align: 'center',
      dataIndex: 'tpScore',
      width: 35,
      render: defaultRender,
    },
    {
      title: '普通分数线',
      align: 'center',
      dataIndex: 'tpScore',
      width: 35,
      render: defaultRender,
    },
  ]

  return column;
}
